server:
    port: 8078
spring:
    application:
        name: microservice-provider-user
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
eureka:
    client:
        healthcheck:
            enabled: true
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        metadata-map:
            zone: ABC
            zhouchao: zhouchaoABC
#eureka.instance.leaseRenewalIntervalInSeconds该配置可以缩短服务注册的时间，当然，生产环境中最好使用默认配置
#        lease-renewal-interval-in-seconds: 10
logging:
    level:
        com:
            zc: debug
        org:
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: trace
                            BasicExtractor: trace
        root: info
management:
    endpoints:
        health:
            sensitive: false
        web:
            exposure:
                include: '*'
managerment:
    security:
        enabled: false
