server:
  port: 8087
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    hostname: 192.168.43.71
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
logging:
  level:
    com.zc.cloud.dao.UserFeignClient: debug
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000