server:
    port: 8096
spring:
    application:
        name: microservice-gateway-zuul-reg-exp
eureka:
    client:
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    server:
        wait-time-in-ms-when-sync-empty: 0
    instance:
        prefer-ip-address: true

