server:
    port: 8089
spring:
    application:
        name: microservice-consumer-movie-feign-hystrix
eureka:
    client:
        healthcheck:
            enabled: true
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    instance:
        hostname: 192.168.43.71
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        prefer-ip-address: true
feign:
    hystrix:
        enabled: true