server:
    port: 8098
eureka:
    client:
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    server:
        wait-time-in-ms-when-sync-empty: 0
    instance:
        prefer-ip-address: true
spring:
    application:
        name: microservice-sidecar
logging:
    level:
        com.netflix: debug
management:
    endpoint:
    endpoints:
        web:
            exposure:
                include: "*"
sidecar:
    health-uri: #异构微服务的链接
    port: 7900