server:
    port: 8097
eureka:
    client:
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    server:
        wait-time-in-ms-when-sync-empty: 0
    instance:
        prefer-ip-address: true
spring:
    application:
        name: microservice-gateway-zuul-fallback
logging:
    level:
        com.netflix: debug
management:
    endpoint:
    endpoints:
        web:
            exposure:
                include: "*"