server:
    port: 18080
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
logging:
    level:
        com:
            zc: debug
        org:
            hibernate:
                type:
                    descriptor:
                        sql:
                            BasicBinder: trace
                            BasicExtractor: trace
        root: info