server:
    port: 8761
spring:
    security:
        basic:
            enabled: true
        user:
            name: user
            password: password123
eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    server:
        wait-time-in-ms-when-sync-empty: 0
        enableSelfPreservation: false
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2