eureka:
    client:
        healthcheck:
            enabled: true
        service-url:
            defaultZone: http://user:password123@localhost:8761/eureka
    instance:
        hostname: 192.168.0.174
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        prefer-ip-address: true
feign:
    hystrix:
        enabled: true
management:
    endpoints:
        health:
            sensitive: true
        web:
            exposure:
                include: "*"
managerment:
    security:
        enabled: false
server:
    port: 8092
spring:
    application:
        name: microservice-consumer-movie-ribbon-with-hystrix-propagation
user:
    userServicePath: http://localhost:18080/simple/